#ifndef _CONSTANT_H
#define _CONSTANT_H

enum Boolean{
	False, True
};

enum KeyCode{
	UP_KEY_CODE = 72, LEFT_KEY_CODE = 75,
	RIGHT_KEY_CODE = 77, DOWN_KEY_CODE = 80,
	SPACE_BAR_KEY_CODE = 32, ESC_KEY_CODE = 27,
	L_KEY_CODE = 108, ENTER_KEY_CODE = 13
};

enum FontColor{
	BLACK, BLUE, GREEN, JADE, RED, PURPLE, YELLOW, WHITE, GRAY,
	LIGHT_BLUE, LIGHT_GREEN, LIGHT_JADE, LIGHT_RED, LIGHT_PURPLE, LIGHT_YELLOW, LIGHT_WHITE,
	WHITE_INVERSION = 240
};

#define DEFAULT_FONT_COLOR LIGHT_WHITE

enum MainMenu{
	NORMAL_CLOCK_MAIN_MENU = 1, ALARM_CLOCK_MAIN_MENU, EXIT_MAIN_MENU
};

#define MILLI_SECONDS_PER_SECOND 1000

#endif